/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"admin" | "dashboard" | "data" | "fullscreen-exit" | "fullscreen" | "group" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "list" | "log" | "person" | "search" | "日志">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"admin" | "dashboard" | "data" | "fullscreen-exit" | "fullscreen" | "group" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "list" | "log" | "person" | "search" | "日志">;
          default: string;
          required: true;
      };
  }>>, {
      name: "admin" | "dashboard" | "data" | "fullscreen-exit" | "fullscreen" | "group" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "list" | "log" | "person" | "search" | "日志";
  }>;
  export const svgNames: ["admin", "dashboard", "data", "fullscreen-exit", "fullscreen", "group", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "list", "log", "person", "search", "日志"];
  export type SvgName = "admin" | "dashboard" | "data" | "fullscreen-exit" | "fullscreen" | "group" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "list" | "log" | "person" | "search" | "日志";
  export default SvgIcon;
}
